// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClThRwlIk9XzYeaxSqAt9_39qxhd2MI_U',
    appId: '1:320845941803:android:2e3162ce9e4fed7b8e2e6e',
    messagingSenderId: '320845941803',
    projectId: 'thaaja-f8107',
    storageBucket: 'thaaja-f8107.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlWu4oLpGQ8TDNpI9fmg3xJnbjFwMekSo',
    appId: '1:320845941803:ios:d3c6554673cee9238e2e6e',
    messagingSenderId: '320845941803',
    projectId: 'thaaja-f8107',
    storageBucket: 'thaaja-f8107.firebasestorage.app',
    androidClientId: '320845941803-7i3n0410tpvbep9ej30r35foagstdp3f.apps.googleusercontent.com',
    iosClientId: '320845941803-drvups39o8r9kp13vo28ho9gmu61up9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.thaaja',
  );
}
