name: thaaja

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
    
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build IPA
      run: flutter build ipa --release --no-codesign
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: build/ios/ipa/*.ipa
